/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed-dim': '#b6c6ee',
        'on-tertiary-fixed-variant': '#5c4217',
        'surface-container': '#edeeef',
        'on-primary-fixed-variant': '#364767',
        'on-secondary-fixed-variant': '#37485b',
        'secondary-container': '#cfe1f8',
        'surface-container-low': '#f3f4f5',
        'primary-container': '#1a2b4a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        secondary: '#4f6073',
        'tertiary-fixed': '#ffddaf',
        'on-tertiary-container': '#af8d5b',
        'outline-variant': '#c5c6cf',
        'surface-variant': '#e1e3e4',
        'on-tertiary-fixed': '#281800',
        'surface-dim': '#d9dadb',
        'on-secondary': '#ffffff',
        background: '#f8f9fa',
        'secondary-fixed-dim': '#b6c8df',
        'tertiary-fixed-dim': '#e7c18a',
        'on-primary': '#ffffff',
        'secondary-fixed': '#d2e4fb',
        'on-primary-fixed': '#081b39',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#0a1d2d',
        outline: '#75777e',
        'tertiary-container': '#3d2700',
        'on-surface-variant': '#44474e',
        'on-primary-container': '#8293b7',
        'surface-tint': '#4e5e80',
        'on-surface': '#191c1d',
        'surface-bright': '#f8f9fa',
        'on-error-container': '#93000a',
        'inverse-primary': '#b6c6ee',
        primary: '#031634',
        'on-background': '#191c1d',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'on-secondary-container': '#536478',
        'surface-container-highest': '#e1e3e4',
        'primary-fixed': '#d8e2ff',
        tertiary: '#221400',
        'surface-container-high': '#e7e8e9',
        surface: '#f8f9fa',
      },
      spacing: {
        base: '8px',
        xl: '80px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xs: '4px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
